### ISSUE TITLE
download_fastycb.sh is empty

### ISSUE THREAD

**Issue by wangyidong3** [robotology/optical-flow-6d-tracking-code#2]
download_fastycb.sh file is empty
Could you please provide the download link or sh file? Thanks.

**Comment by xEnVrE** [comment]
Dear @wangyidong3,

thanks for reaching out.

The dataset is not available yet, we will make it available in the next weeks.

I'll update this issue once it is available.

**Comment by wangyidong3** [comment]
Thanks, looking forward to its release

**Comment by xEnVrE** [comment]
Dear @wangyidong3,

a specific repository for the dataset is now available at https://github.com/hsp-iit/fast-ycb. You can download it by following the instructions in https://github.com/hsp-iit/fast-ycb#how-to-obtain-the-dataset.

If you already downloaded the docker image of ROFT, you should `docker pull`-it again as there were changes from our last chat.

Let me know if this answers your question so that I can close the issue.

Thanks

**Comment by xEnVrE** [comment]
I will close the issue.

Please feel free to re-open it in case of further doubts.
